kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.27.1
cgroupDriver: cgroup2fs
controlPlaneEndpoint: "example.com:6443"
networking:
  podSubnet: "10.244.0.0/16" 


